version: 2
jobs:
  build:
    working_directory: /tmp/build
    docker:
      - image: spikerlabs/scala-sbt:scala-2.12.1-sbt-0.13.13
    steps:
      - checkout
      - setup_remote_docker
      - test:
          name: Run test
          command: sbt verify
      - deploy:
          name: Publish to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apk add --no-cache docker
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
              sbt docker:publish
              curl --user ${CIRCLE_API_TOKEN}: \
                --data build_parameters[CIRCLE_JOB]=deploy_to_gce \
                --data revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
            fi
  deploy_to_gce:
    working_directory: /
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Deploy to GCE
          command: |
            echo $GCE_SERVICE | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project pairing-buddy
            gcloud container clusters get-credentials pairing-buddy-2 --zone us-east1-d --project pairing-buddy
            kubectl rolling-update pairing-buddy-latest --image=asarturas/pairing-buddy:latest --image-pull-policy Always